# File name: database.py - connects to database.
import os
import sqlite3
from pathlib import Path
from typing import Generator

from app.config import settings


def get_db_connection() -> sqlite3.Connection:
    """Create and return a SQLite connection with row factory enabled."""
    db_path = Path(settings.DATABASE_PATH)
    db_path.parent.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(str(db_path), check_same_thread=False)
    conn.row_factory = sqlite3.Row
    return conn


def get_db() -> Generator[sqlite3.Connection, None, None]:
    """FastAPI dependency for database connection lifecycle management."""
    conn = get_db_connection()
    try:
        yield conn
    finally:
        conn.close()


def init_db_and_storage() -> None:
    """Initialize database tables, seed sample records, and create sample files."""
    # Ensure storage directories exist with sample documents
    receipts_dir = settings.DOCUMENTS_BASE_DIR / "receipts"
    contracts_dir = settings.DOCUMENTS_BASE_DIR / "contracts"
    receipts_dir.mkdir(parents=True, exist_ok=True)
    contracts_dir.mkdir(parents=True, exist_ok=True)
    settings.TEMPLATES_DIR.mkdir(parents=True, exist_ok=True)

    # Create sample receipt and template files
    sample_receipt = receipts_dir / "INV-2026-001.txt"
    if not sample_receipt.exists():
        sample_receipt.write_text(
            "FINPULSE ENTERPRISE RECEIPT\n"
            "Invoice: INV-2026-001\n"
            "Customer: Acme Global Corp\n"
            "Amount: $14,500.00 USD\n"
            "Status: PAID\n"
        )

    sample_template = settings.TEMPLATES_DIR / "quarterly_summary.html"
    if not sample_template.exists():
        sample_template.write_text(
            "<div class='summary-box'><h3>Quarterly Financial Summary</h3>"
            "<p>Generated by FinPulse Reporting Engine</p></div>"
        )

    conn = get_db_connection()
    cursor = conn.cursor()

    cursor.execute(
        """
        CREATE TABLE IF NOT EXISTS invoices (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            invoice_number TEXT NOT NULL UNIQUE,
            customer_name TEXT NOT NULL,
            billing_email TEXT NOT NULL,
            amount REAL NOT NULL,
            currency TEXT DEFAULT 'USD',
            status TEXT NOT NULL,
            notes TEXT,
            created_at TEXT NOT NULL
        )
        """
    )

    cursor.execute(
        """
        CREATE TABLE IF NOT EXISTS audit_logs (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            actor TEXT NOT NULL,
            action TEXT NOT NULL,
            resource TEXT NOT NULL,
            details TEXT,
            timestamp TEXT NOT NULL
        )
        """
    )

    # Seed initial data if empty
    cursor.execute("SELECT COUNT(*) as cnt FROM invoices")
    row = cursor.fetchone()
    if row and row["cnt"] == 0:
        sample_invoices = [
            (
                "INV-2026-001",
                "Acme Global Corp",
                "ap@acmeglobal.example.com",
                14500.00,
                "USD",
                "PAID",
                "Q1 Enterprise License renewal",
                "2026-01-15 09:30:00",
            ),
            (
                "INV-2026-002",
                "Stark Logistics Ltd",
                "finance@starklogistics.example.com",
                8250.50,
                "USD",
                "PENDING",
                "Freight settlement API integration fee",
                "2026-02-03 14:15:00",
            ),
            (
                "INV-2026-003",
                "Wayne Enterprises",
                "billing@wayne.example.com",
                49000.00,
                "USD",
                "OVERDUE",
                "Dedicated cloud node deployment",
                "2026-02-19 11:00:00",
            ),
            (
                "INV-2026-004",
                "Globex Corporation",
                "accounts@globex.example.com",
                3120.00,
                "EUR",
                "PAID",
                "Monthly compliance audit add-on",
                "2026-03-01 16:45:00",
            ),
        ]
        cursor.executemany(
            """
            INSERT INTO invoices (
                invoice_number, customer_name, billing_email, amount, currency, status, notes, created_at
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
            """,
            sample_invoices,
        )

        cursor.execute(
            """
            INSERT INTO audit_logs (actor, action, resource, details, timestamp)
            VALUES (?, ?, ?, ?, ?)
            """,
            (
                "system@finpulse.internal",
                "SEED_DATABASE",
                "invoices",
                "Initialized default enterprise invoice ledger",
                "2026-03-01 08:00:00",
            ),
        )

    conn.commit()
    conn.close()
